# Generated by Django 5.2.7 on 2025-10-09 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0002_alter_producto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('iva', models.DecimalField(decimal_places=2, default=19, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje_max', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sucursal', models.CharField(blank=True, max_length=100, null=True)),
                ('bodega', models.CharField(blank=True, max_length=100, null=True)),
                ('condicion', models.CharField(choices=[('cheque', 'Cheque'), ('cheque_pie_30_60', 'Cheque Pie-30-60'), ('credito', 'Crédito'), ('credito_pie_30_60', 'Crédito Pie-30-60'), ('efectivo', 'Efectivo'), ('mixto', 'Mixto'), ('sodexo', 'Pago Sodexo'), ('tarjeta_credito', 'Tarjeta Crédito'), ('debito', 'Débito'), ('transferencia', 'Transferencia')], default='efectivo', max_length=50)),
                ('unidad_negocio', models.CharField(choices=[('administracion', 'Administración'), ('repuestos', 'Repuestos'), ('servicio_tecnico', 'Servicio Técnico'), ('ventas', 'Ventas')], default='ventas', max_length=50)),
                ('centro_costo', models.CharField(choices=[('administracion', 'Administración'), ('servicio_tecnico', 'Servicio Técnico'), ('ventas', 'Ventas')], default='ventas', max_length=50)),
                ('rechazo', models.TextField(blank=True, null=True)),
                ('entrega', models.PositiveIntegerField(default=7)),
                ('validez', models.PositiveIntegerField(default=30)),
                ('nota_venta', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('oc_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('flete_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('exento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rentabilidad_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('nula', 'Nula'), ('parcial', 'Parcial Confección')], default='pendiente', max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='clients.cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mts2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('flete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('moneda', models.CharField(default='CLP', max_length=10)),
                ('plazo', models.PositiveIntegerField(default=0)),
                ('precio_ref', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_ref', models.DecimalField(decimal_places=2, max_digits=12)),
                ('p_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rentabilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('neto_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exento_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bruto_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vendido', models.BooleanField(default=False)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='quotes.cotizacion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='products.producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
