# Generated by Django 5.2.7 on 2025-10-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='cotizaciondetalle',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Cotización', 'verbose_name_plural': 'Detalles de Cotizaciones'},
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='moneda',
            field=models.CharField(choices=[('CLP', 'Peso Chileno'), ('USD', 'Dólar'), ('EUR', 'Euro')], default='CLP', max_length=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nota_interna',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='referencia_interna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='entrega',
            field=models.PositiveIntegerField(default=7, help_text='Días estimados de entrega'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='validez',
            field=models.PositiveIntegerField(default=30, help_text='Días de validez de la cotización'),
        ),
    ]
