# Generated by Django 5.2.7 on 2025-10-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelOptions(
            name='cotizaciondetalle',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='nota_interna',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='referencia_interna',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='entrega',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='moneda',
            field=models.CharField(default='CLP', max_length=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='validez',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
