# Generated by Django 5.2.7 on 2025-10-08 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clients.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='region',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='clients.region'),
            preserve_default=False,
        ),
    ]
