# Generated by Django 5.2.7 on 2025-10-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_cliente_ciudad_cliente_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='ciudad',
            new_name='city',
        ),
    ]
