# Generated by Django 5.2.7 on 2025-10-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_ciudad_cliente_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='city',
        ),
    ]
