# Generated by Django 5.2.7 on 2025-10-09 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=100)),
                ('p_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_con_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articulo_activo', models.BooleanField(default=True)),
                ('control_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hora', models.CharField(max_length=50)),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arriendo', to='products.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoContabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_compra', models.CharField(max_length=100)),
                ('cuenta_venta', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_moneda', models.CharField(default='CLP', max_length=20)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contabilidad', to='products.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=100)),
                ('garantia', models.CharField(max_length=100)),
                ('proveedor_garantia', models.CharField(max_length=100)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce', to='products.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigencia_dias', models.PositiveIntegerField()),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fabricacion', to='products.producto')),
            ],
        ),
    ]
