# Generated by Django 5.2.7 on 2025-10-09 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('herramienta', 'Herramienta'), ('maquinaria', 'Maquinaria'), ('insumo', 'Insumo'), ('servicio', 'Servicio'), ('otro', 'Otro')], max_length=50)),
                ('p_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_con_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articulo_activo', models.BooleanField(default=True)),
                ('control_stock', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProductoArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo_hora', models.CharField(max_length=50)),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arriendo', to='products.producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoContabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cuenta_compra', models.CharField(max_length=100)),
                ('cuenta_venta', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('lt', 'Litro'), ('m2', 'Metro cuadrado'), ('m3', 'Metro cúbico')], max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_moneda', models.CharField(choices=[('CLP', 'Peso Chileno'), ('USD', 'Dólar'), ('EUR', 'Euro')], default='CLP', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contabilidad', to='products.producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('condicion', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('refabricado', 'Refabricado')], default='nuevo', max_length=50)),
                ('garantia', models.CharField(max_length=100)),
                ('proveedor_garantia', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce', to='products.producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigencia_dias', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fabricacion', to='products.producto')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
